$(document).ready(function(){
    $(".place01_1").click(function(){
        $("#bglayer").show();
        $("#overlayer01_01").show();
    });
    $(".place01_2").click(function(){
        $("#bglayer").show();
        $("#overlayer01_02").show();
    });
    $(".place01_3").click(function(){
        $("#bglayer").show();
        $("#overlayer01_03").show();
    });
    $(".place01_4").click(function(){
        $("#bglayer").show();
        $("#overlayer01_04").show();
    });
    $(".place01_5").click(function(){
        $("#bglayer").show();
        $("#overlayer01_05").show();
    });
    $(".place01_6").click(function(){
        $("#bglayer").show();
        $("#overlayer01_06").show();
    });
    $(".place01_7").click(function(){
        $("#bglayer").show();
        $("#overlayer01_07").show();
    });
    $(".place02_1").click(function(){
        $("#bglayer").show();
        $("#overlayer02_01").show();
    });
    $(".place02_2").click(function(){
        $("#bglayer").show();
        $("#overlayer02_02").show();
    });
    $(".place02_3").click(function(){
        $("#bglayer").show();
        $("#overlayer02_03").show();
    });
    $(".place02_4").click(function(){
        $("#bglayer").show();
        $("#overlayer02_04").show();
    });
    $(".place02_5").click(function(){
        $("#bglayer").show();
        $("#overlayer02_05").show();
    });
    $(".place02_6").click(function(){
        $("#bglayer").show();
        $("#overlayer02_06").show();
    });
    $(".place03_1").click(function(){
        $("#bglayer").show();
        $("#overlayer03_01").show();
    });
    $(".place03_2").click(function(){
        $("#bglayer").show();
        $("#overlayer03_02").show();
    });
    $(".place03_3").click(function(){
        $("#bglayer").show();
        $("#overlayer03_03").show();
    });
    $(".place03_4").click(function(){
        $("#bglayer").show();
        $("#overlayer03_04").show();
    });
    $(".place04_1").click(function(){
        $("#bglayer").show();
        $("#overlayer04_01").show();
    });
    $(".place04_2").click(function(){
        $("#bglayer").show();
        $("#overlayer04_02").show();
    });

    $("#bglayer").click(function(){
        $(this).hide();
        $("#overlayer01_01").hide();
        $("#overlayer01_02").hide();
        $("#overlayer01_03").hide();
        $("#overlayer01_04").hide();
        $("#overlayer01_05").hide();
        $("#overlayer01_06").hide();
        $("#overlayer01_07").hide();
        $("#overlayer02_01").hide();
        $("#overlayer02_02").hide();
        $("#overlayer02_03").hide();
        $("#overlayer02_04").hide();
        $("#overlayer02_05").hide();
        $("#overlayer02_06").hide();
        $("#overlayer03_01").hide();
        $("#overlayer03_02").hide();
        $("#overlayer03_03").hide();
        $("#overlayer03_04").hide();
        $("#overlayer04_01").hide();
        $("#overlayer04_02").hide();
    });
});